name: Tabelki
favicon: null
layout_spectrum: 0.75971
typography_spectrum: 0.04226
title: Tabelki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0581861468963325
  lightness: 0.2004875021521002
  saturation: 0.4828241483774036
  rhythmicContrast: 0.6002376901451498
purpose: []
